### PR TITLE
Python 3.x and Python 2.7 cross version support

### PR DESCRIPTION
**Pull request by timtadh**
Used `modernize` and `2to3` to achieve cross support. Now pulls in six as a dependency. This pr supersedes https://github.com/timtadh/zhang-shasha/pull/26

### CODE REVIEW

**Comment by timtadh** [comment]
@guludo can you test this on your end? I tested on 2.7 and 3.4.

**Comment by timtadh** [comment]
@irskep if you want to test as well or have any suggestions let me know. I haven't done a cross 2/3 library before.

**Comment by irskep** [comment]
Note to self, test this on Jan 29.

**Comment by borgr** [comment]
hey, I see this branch hasn't been edited lately, does it mean there is a way to use the library in python3?

**Comment by timtadh** [comment]
@borgr I am waiting for someone to test this before merging. I tested on 2.7.x and 3.4.x. I do not use python 3 in my work right now so I didn't want to merge without some verification that it is working as expected from someone who cares.

**Comment by gyfis** [comment]
Hello, and thanks for this repo. For what it's worth, I've just run the sample example from README under Python 3.5  (with the slight change from `print dist` to `print(dist)`) with zss from this branch, and it went through without an error.

**Comment by timtadh** [comment]
@gyfis : great I will merge when I get back from vacation on thursday.

**Comment by guludo** [comment]
Thank you! I'm sorry I couldn't help with testing. Didn't have much time...

**Comment by petrbel** [comment]
Hi guys, have you considered setting up some CI? I have positive experience with TravisCI, but any other should do the work as well. This could help keeping the code valid for both pythons :)

**Comment by timtadh** [comment]
@petrbel open an issue and I will add it to my todo list.

**Pull request merged**
