### PR TITLE
Removed steve's email from docs by request

### PR DESCRIPTION
**Pull request by timtadh**
@irskep let me know if this is ok.

### CODE REVIEW

**Comment by timtadh** [comment]
I will also need to remember how to push to read the docs. Did you do that or did I? I am not actually sure.

**Comment by irskep** [comment]
Great! I would actually recommend removing yours as well and just pointing everyone to GitHub issues.

For RtD...I actually don't know. It might be a git commit hook. The current version of the docs is 1.1.4, whereas PyPI points to pythonhosted.org, which I doubt you keep updated.

**Comment by irskep** [comment]
Looks like I do have the RtD credentials. I can update and/or add you to the project. Do you have a username there?

**Comment by irskep** [comment]
You're already a maintainer.

**Comment by timtadh** [comment]
Ok. I will have to take a look tonight when I have my other computer.

**Comment by timtadh** [comment]
I triggered a build on this manually in the read the docs interface.

**Comment by timtadh** [comment]
ok looks like you are gone from the read the docs as well. Sorry this took me a while.

**Pull request merged**
