### PR TITLE
Return operation history

### PR DESCRIPTION
**Pull request by erickrf**
I introduced an optional parameter `return_operations`, false by default, that makes zss.distance and zss.simple_distance return a tuple `(cost, operation_history)`. The operation history is a list of `Operation` instances, a simple class I added to `compare.py`.

### CODE REVIEW

**Comment by timtadh** [comment]
Hi @erickrf ,

This looks pretty good. Can you add some tests for a few simple trees? This will help in two ways

1. Ensure that the feature keeps working after future changes.
2. Build confidence in the implementation.

Thank you again for working on this. You can also add yourself to the LICENSE file.

**Comment by erickrf** [comment]
Ok, there it is. I hope these tests are enough.

No need to add my name to the License; this contribution is rather marginal.

**Comment by timtadh** [comment]
Ok merged. I did add you to the license file since you made a pretty important (from my perspective) functional change. If you have other ideas for this project let me know.

**Comment by erickrf** [comment]
Ok, thank you!

**Pull request merged**
