### PR TITLE
Support python3

### PR DESCRIPTION
**Pull request by guludo**
The changes were done automatically with 2to3.

This addresses issue #25.

### CODE REVIEW

**Comment by timtadh** [comment]
Before I pull this down an take a look do the tests pass?

**Comment by guludo** [comment]
I tested here and they pass. For some test files, I had to write a script that run the test functions. I'm not sure if that was the correct approach.

**Comment by timtadh** [comment]
@guludo I will take a look. The correct way to run the tests is with nose:

    $ nosetests -v

**Comment by guludo** [comment]
Thanks for the tip :)

**Comment by timtadh** [comment]
Looks ok to me. I am going to merge.

**Comment by timtadh** [comment]
Actually. I can't merge. Because it doesn't also seamlessly support 2.7. I need to look into this more closely. Specifically, I noticed the use of range in place of xrange which may cause memory errors on 2.7.

**Comment by timtadh** [comment]
I am closing this pr in favor of a new one with my additions.

**Pull request closed without merging**
